services:

  api:
    image: ghcr.io/nani19dev/imolage-backend:latest
    restart: always
    networks:
      - dokploy-network
    ports:
      - "8000:8000"

networks:
  dokploy-network:
    external: true