services:
  django-app:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 3 # Scale for production
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.django.rule=Host(`imolage.backendvps.eu`)" # Replace with your production domain
        - "traefik.http.services.django.loadbalancer.server.port=8000"
        - "traefik.http.routers.django.entrypoints=web"
        - "traefik.http.routers.django.tls.certresolver=myresolver" # Enable HTTPS
    environment:
      - DOMAIN=backendvps.eu # Replace with your production domain
      #- SECRET_KEY_VALUE=${SECRET_KEY_VALUE}
      #- DB_HOST=${DB_HOST} 
      #- DB_NAME=${DB_NAME} 
      #- DB_USER=${DB_USER} 
      #- DB_PORT=${DB_PORT} 
      #- DB_PWD=${DB_PWD} 
    networks:
      - web